repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      language_version: python3.7
      files: bus
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args: ['--config=setup.cfg']
      files: bus
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
