version: '3.7'
services:
# ---------------------------------------
  graphite:
    container_name: graphite
    restart: unless-stopped
    build: ./docker/graphite
    hostname: graphite
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
    volumes:
      - ./var/graphite_whisper:/opt/graphite/storage/whisper
      - ./var/graphite_conf:/opt/graphite/conf
    expose:
      - "80"
    ports:
      - "${GRAPHITE_PORT}:8125/udp"
# ---------------------------------------
  grafana:
    container_name: grafana
    restart: unless-stopped
    env_file: ./.env
    image: grafana/grafana:6.5.1-ubuntu
    hostname: grafana
    volumes:
      - ./var/grafana-storage:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "2"
    user: "root"
    links:
      - graphite:graphite
# -----------------------------------
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
      args:
        DOMAIN: $DOMAIN
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "10"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./var/letsencrypt/etc:/etc/letsencrypt
      - ./var/letsencrypt/dh-param/dhparam.pem:/certs/dhparam.pem
      - ./var/letsencrypt/site:/usr/share/nginx/html
      - ./var/logs/nginx:/var/log/nginx
# -----------------------------------
  letsencrypt-nginx:
     container_name: 'letsencrypt-nginx'
     build:
       context: ./docker
       dockerfile: letsencrypt-nginx/Dockerfile
       args:
         DOMAIN: $DOMAIN
     ports:
       - "80:80"
     volumes:
       - ./var/letsencrypt/site:/usr/share/nginx/html
